import { CollectionConfig } from "payload";

const Products: CollectionConfig = {
  slug: "products",
  admin: {
    useAsTitle: "product",
  },
		access: {
		  read: ({ req, id }) => true,
		  update: ({ req, id }) => req.user?.role === 'admin' || req.user?.id === id,
		  delete: ({ req }) => req.user?.role === 'admin',
		},
  fields: [
    {
      name: "tag",
      type: 'select', // required
      hasMany: true,
      admin: {
        isClearable: true,
        isSortable: true, // use mouse to drag and drop different values, and sort them according to your choice
      },
      options: [
        { label: 'Network Security Multi-Segmentation', value: 'network-security-multi-segmentation',},
        { label: 'Tastaturen', value: 'tastaturen',},
        { label: 'Esports', value: 'esports',},
        { label: 'Sneaker', value: 'sneaker',},
        { label: 'Sita Chronicles', value: 'sita-chronicles',},
        { label: 'Asics', value: 'asics',},
        { label: 'Modern', value: 'modern',},
        { label: 'Damen-Sandalen', value: 'damen-sandalen',},
        { label: 'Arbeitsspeicher', value: 'arbeitsspeicher',},
        { label: 'Headphones', value: 'headphones',},
        { label: 'Pulse', value: 'pulse',},
        { label: 'Micro-SD', value: 'micro-sd',},
        { label: 'Grafikkarten', value: 'grafikkarten',},
        { label: 'Gaming', value: 'gaming',},
        { label: 'ASUS', value: 'asus',},
        { label: 'Prozessoren', value: 'prozessoren',},
        { label: 'AMD', value: 'amd',},
        { label: 'AM4', value: 'am4',},
        { label: 'AM5', value: 'am5',},
        { label: 'Intel', value: 'intel',},
        { label: 'LGA1700', value: 'lga1700',},
        { label: 'Thermalright', value: 'thermalright',},
        { label: 'Gips', value: 'gips',},
        { label: 'Q3', value: 'Q3',},
        { label: 'Q4', value: 'Q4',},
        { label: 'Mörtelverfestiger', value: 'moertelverfestiger',},
        { label: 'Schlüsselanhänger', value: 'schluesselanhaenger',},
        { label: 'Peripherie', value: 'peripherie',},
        { label: 'Mäuse', value: 'maeuse',},
        { label: 'Promotion', value: 'promotion',},
        { label: 'Dubai-Schokolade', value: 'dubai-schokolade',},
        { label: 'TShirts', value: 'tshirts',},
        { label: 'Barbie', value: 'barbie',},
        { label: 'Puppen', value: 'puppen',},
        { label: 'Armschale', value: 'armschale',},
        { label: 'Kunstpelze', value: 'kunstpelze',},
        { label: 'Beliebt', value: 'beliebt',},
        { label: 'Ballkleider', value: 'ballkleider',},
        { label: 'Handtuch', value: 'handtuch',},
        { label: 'Gehäuse', value: 'gehaeuse',},
        { label: 'Corsair', value: 'corsair',},
        { label: 'NZXT', value: 'nzxt',},
        { label: 'Class 10', value: 'class10',},
        { label: 'Kabellos', value: 'kabellos',},
        { label: 'Gigabyte', value: 'gigabyte',},
        { label: 'MSI', value: 'msi',},
        { label: 'SSD NVMe', value: 'ssd-nvme',},
        { label: 'Integral', value: 'integral',},
        { label: 'Monitore', value: 'monitore',},
        { label: 'Diversey', value: 'diversey',},
        { label: 'BenQ', value: 'benq',},
        { label: 'LG Electronics', value: 'lg-electronics',},
        { label: 'Curved', value: 'curved',},
        { label: 'Minifire', value: 'minifire',},
        { label: 'Netzteile', value: 'netzteile',},
        { label: 'Lian-Li', value: 'lianli',},
        { label: 'Valve Software', value: 'valve',},
        { label: 'Steamdeck', value: 'steamdeck',},
        { label: 'ID Software', value: 'id-software',},
        { label: 'VFR', value: 'vfr',},
        { label: 'Dell', value: 'dell',},
        { label: 'Raspberry PI', value: 'raspberrypi',},
        { label: 'Spiele', value: 'spiele',},
        { label: 'KONAMI', value: 'konami',},
        { label: 'CAPCOM', value: 'capcom',},
        { label: 'Resident Evil', value: 'resident-evil',},
        { label: 'SONY', value: 'sony',},
        { label: 'PS4', value: 'playstation4',},
        { label: 'PS5', value: 'playstation5',},
        { label: 'Portal', value: 'portal',},
        { label: 'PS5-Pro', value: 'ps5-pro',},
        { label: 'Dual Sense', value: 'dualsense',},
        { label: 'PS4 Release', value: 'ps4-release',},
        { label: 'PS5 Release', value: 'ps5-release',},
        { label: 'NINTENDO', value: 'nintendo',},
        { label: 'Slim', value: 'slim',},
        { label: 'Digital Edition', value: 'digitaledition',},
        { label: 'Zelda', value: 'zelda',},
        { label: 'Mario', value: 'mario',},
        { label: 'Donkey Kong', value: 'donkey-kong',},
        { label: 'Switch Spiele', value: 'switch-spiele',},
        { label: 'Switch2 Spiele', value: 'switch2-spiele',},
        { label: 'Switch', value: 'switch',},
        { label: 'Switch2', value: 'switch2',},
        { label: 'Spielkonsolen', value: 'spielkonsolen',},
        { label: 'Konsole', value: 'konsole',},
        { label: 'Pro Controller', value: 'pro-controller',},
        { label: 'JoyCon', value: 'joycon',},
        { label: 'Blau / Neon Gelb', value: 'blau-neon-gelb',},
        { label: 'Neon Gruen / Neon Pink', value: 'neon-gruen-neon-pink',},
        { label: 'Neon Lila / Neon Orange', value: 'neon-lila-neon-orange',},
        { label: 'Neon Rot / Neon Blau', value: 'neon-rot-neon-blau',},
        { label: 'Neon Rot', value: 'neon-rot',},
        { label: 'Kamera', value: 'kamera',},
        { label: 'JoyCon2', value: 'joycon2',},
        { label: 'Digital Download', value: 'digital-download',},
        { label: 'GTA', value: 'grand-theft-auto',},
        { label: 'Skybound', value: 'skybound',},
        { label: 'Adventure', value: 'adventure',},
        { label: 'PC Spiele', value: 'pc-spiele',},
        { label: 'Blizzard', value: 'blizzard',},
        { label: 'WoW', value: 'world-of-warcraft',},
      ],
      required: false,
    },
//    {
//      name: 'tags',
//      type: 'array',
//      admin: {
//        components: {
//          Field: '@/collections/CustomFields/CustomTagsArrayFieldClient',
//        },
//      },
//      fields: [
//        {
//          name: 'tag',
//          type: 'text',
//        },
//      ],
//    },
    {
      name: "product",
      type: "text",
      required: true,
    },
    {
      name: "shop",
      type: "text",
      required: false,
    },
    {
      name: "link",
      type: "text",
      required: false,
    },
    {
      name: "price0",
      type: "text",
      required: false,
    },
    {
      name: "price1",
      type: "text",
      required: false,
    },
    {
      name: "price2",
      type: "text",
      required: false,
    },
    {
      name: "image",
      type: "text",
      required: false,
    },
    {
      name: "importance",
      type: "text",
      required: false,
    },
  ],
};

export default Products;